import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const lexendExa = localFont({
  src: '../public/fonts/LexendExa.ttf',
  variable: '--font-lexend-exa',
  display: 'swap',
})

const lexendDeca = localFont({
  src: '../public/fonts/LexendDeca-Light.ttf',
  variable: '--font-lexend-deca',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "CIT - Takshashila 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </head>
      <body className={`${lexendExa.variable} ${lexendDeca.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
